import type { NextPage } from 'next';
import { SubmitHandler } from "react-hook-form";
import { useRouter } from 'next/router';
import Head from 'next/head';
import OsForm from '../../components/OsForm';

type Inputs = {
  clienteId: number,
  problemaRelatado: string,
  colaboradorId: number,
};

const CadastrarOs: NextPage = () => {
  const router = useRouter();

  const onSubmit: SubmitHandler<Inputs> = async (data) => {
    await fetch('http://localhost:3001/ordens', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(data)
    })

    router.push('/os');
  };
  return (
    <div>
      <Head>
        <title>PredialX - Cadastro de Ordens de Serviço</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Cadastrar Ordens de Serviço</p>
      <div>
        <OsForm onSubmit={onSubmit} buttonName="Cadastrar" />
      </div>
    </div>
  )
}

export default CadastrarOs;