import type { NextPage } from 'next';
import { useRouter } from 'next/router';
import { useForm, SubmitHandler } from "react-hook-form";
import Head from 'next/head';

type Inputs = {
  nome: string,
};

const CadastrarCliente: NextPage = () => {
  const router = useRouter();
  const { register, handleSubmit } = useForm<Inputs>();
  const onSubmit: SubmitHandler<Inputs> = async (data) => {
    await fetch('http://localhost:3001/cliente', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(data)
    })

    router.push('/');
  };

  return (
    <div>
      <Head>
        <title>PredialX - Cadastro de Clientes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Cadastrar clientes</p>
      <div>
        <form onSubmit={handleSubmit(onSubmit)}>
          <label>
            Nome:
            <input { ...register("nome", { required: true })} />
          </label>
          <button type="submit">Criar</button>
        </form>
      </div>
    </div>
  )
}

export default CadastrarCliente;