import type { NextPage } from 'next';
import { useForm, SubmitHandler } from "react-hook-form";
import { useRouter } from 'next/router';
import Head from 'next/head';

type Inputs = {
  nome: string,
  email: string,
  senha: string,
};

const CadastrarColaborador: NextPage = () => {
  const router = useRouter();

  const { register, handleSubmit } = useForm<Inputs>();

  const onSubmit: SubmitHandler<Inputs> = async (data) => {
    await fetch('http://localhost:3001/colaborador', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(data)
    })

    router.push('/colaborador');
  };
  return (
    <div>
      <Head>
        <title>PredialX - Cadastro de Colaboradores</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Cadastrar colaboradores</p>
      <div>
        <form onSubmit={handleSubmit(onSubmit)}>
          <label>
            Nome:
            <input { ...register("nome", { required: true })} />
          </label>
          <label>
            Email:
            <input { ...register("email", { required: true })} />
          </label>
          <label>
            Senha:
            <input { ...register("senha", { required: true })} />
          </label>
            <button type="submit">Criar</button>
        </form>
      </div>
    </div>
  )
}

export default CadastrarColaborador;