import type { NextPage } from 'next';
import { useForm, SubmitHandler } from "react-hook-form";
import { useRouter } from 'next/router';
import Head from 'next/head';

type Inputs = {
  clienteId: number,
  problemaRelatado: string,
  colaboradorId: number,
};

const CadastrarOs: NextPage = () => {
  const router = useRouter();

  const { register, handleSubmit } = useForm<Inputs>();

  const onSubmit: SubmitHandler<Inputs> = async (data) => {
    await fetch('http://localhost:3001/ordens', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(data)
    })

    router.push('/os');
  };
  return (
    <div>
      <Head>
        <title>PredialX - Cadastro de Ordens de Serviço</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Cadastrar Ordens de Serviço</p>
      <div>
        <form onSubmit={handleSubmit(onSubmit)}>
          <label>
            Id do cliente:
            <input { ...register("clienteId", { required: true })} />
          </label>
          <label>
            Qual foi o problema relatado?
            <textarea { ...register("problemaRelatado", { required: true })} />
          </label>
          <label>
            Id do colaborador:
            <input { ...register("colaboradorId", { required: true })} />
          </label>
            <button type="submit">Criar</button>
        </form>
      </div>
    </div>
  )
}

export default CadastrarOs;