import type { NextPage } from 'next';
import { useRouter } from 'next/router';
import { useForm, SubmitHandler } from "react-hook-form";
import Head from 'next/head';

type Inputs = {
  name: string,
};

const CadastrarCliente: NextPage = () => {
  const router = useRouter();
  const { register, handleSubmit } = useForm<Inputs>();
  const onSubmit: SubmitHandler<Inputs> = data => console.log(data);

  return (
    <div>
      <Head>
        <title>PredialX - Cadastro de Clientes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <form onSubmit={handleSubmit(onSubmit)}>
          <label>
            Nome:
            <input { ...register("name", { required: true })} />
          </label>
          <button type="submit">Criar</button>
        </form>
      </div>
    </div>
  )
}

export default CadastrarCliente;