import type { NextPage } from 'next';
import { useForm, SubmitHandler } from "react-hook-form";
import { useRouter } from 'next/router';
import Head from 'next/head';

type Inputs = {
  name: string,
  email: string,
  senha: string,
};

const CadastrarColaborador: NextPage = () => {
  const { register, handleSubmit } = useForm<Inputs>();
  const onSubmit: SubmitHandler<Inputs> = data => console.log(data);
  return (
    <div>
      <Head>
        <title>PredialX - Cadastro de Colaboradores</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Cadastrar colaboradores</p>
      <div>
        <form onSubmit={handleSubmit(onSubmit)}>
          <label>
            Nome:
            <input { ...register("name", { required: true })} />
          </label>
          <label>
            Email:
            <input { ...register("email", { required: true })} />
          </label>
          <label>
            Senha:
            <input { ...register("senha", { required: true })} />
          </label>
            <button type="submit">Criar</button>
        </form>
      </div>
    </div>
  )
}

export default CadastrarColaborador;