import type { NextPage } from 'next';
import Head from 'next/head';

const CadastrarOs: NextPage = () => {
  return (
    <div>
      <Head>
        <title>PredialX - Cadastro de Ordens de Serviço</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Cadastrar Ordens de Serviço</p>
    </div>
  )
}

export default CadastrarOs;