import Head from 'next/head';
import React from 'react';
import Dashboard from '../components/Dashboard';

const Home: React.FC = () => {
  // useAuthentication();
  return (
    <div className="m-auto">
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex w-screen md:max-w-xl lg:max-w-5xl h-screen">
        <Dashboard />
      </main>
    </div>
  );
};

export default Home;
