import Head from 'next/head';
import React from 'react';
import Register from '../components/Register';

const Home: React.FC = () => {
  // useAuthentication();
  return (
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>PredialX</h1>
        <Register />
      </main>
    </div>
  );
};

export default Home;
