import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect } from 'react';
import LoginForm from '../components/LoginForm';

const Login: NextPage = () => {
  useEffect(() => {
    const userLocalStorage = JSON.parse(localStorage.getItem('user') || '{}');

    if (Object.keys(userLocalStorage).length === 0) {
      localStorage.setItem('user', '{}');
    }
  }, []);
  return (
    <div className="w-full h-screen flex items-center justify-center">
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginForm />
    </div>
  );
};

export default Login;
