import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';

const MinhaConta: NextPage = () => {
  const [user, setUser] = useState({
    email: '',
    password: '',
  });
  useEffect(() => {
    const dados = JSON.parse(localStorage.getItem('user') || ('{}'));
    setUser(dados);
  }, []);
  return (
    <div className="py-8 px-10 w-screen max-w-5xl h-screen">
      <Head>
        <title>Minha conta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p className="text-3xl font-semibold">
        Minha conta
      </p>
      <h3 className="mt-4">
        {`Email: ${user.email}`}
      </h3>
    </div>
  );
};

export default MinhaConta;
