import type { NextPage } from 'next';
import Head from 'next/head';
import Register from '../components/Register';
import useAuthentication from '../hooks/useAuthentication';

const Home: NextPage = () => {
  useAuthentication();

  return (
    <div>
      <Head>
        <title>PredialX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Register />
      </main>
    </div>
  )
}

export default Home;
