import type { NextPage } from 'next';
import Head from 'next/head';
import Form from '../components/Form';

const Login: NextPage = () => {
  return (
    <div>
      <Head>
        <title>PredialX - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>Login</p>
      <Form />
    </div>
  )
}

export default Login;