import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect } from 'react';
import LoginForm from '../components/LoginForm';

const Login: NextPage = () => {
  useEffect(() => {
    localStorage.setItem('data', '{}');
  }, []);
  return (
    <div>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p className='text-2xl'>Login</p>
      <LoginForm />
    </div>
  )
}

export default Login;